name: 'publish'
on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CONTROL_REPO_TOKEN }}
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install submodule dependencies
        working-directory: ./cli
        run: cd packages/wvcdm && npm ci

      - name: Install app dependencies
        working-directory: ./cli
        run: npm ci

      - name: Get package name and version
        working-directory: ./cli
        run: |
          test -n $(node -p -e "require('./package.json').name") &&
          test -n $(node -p -e "require('./package.json').version") &&
          echo PACKAGE_NAME=$(node -p -e "require('./package.json').name") >> $GITHUB_ENV &&
          echo PACKAGE_VERSION=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV || exit 1

      - name: Generating executables
        working-directory: ./cli
        run: npm run build --if-present

      - name: Compressing builds
        working-directory: ./cli
        run: |
          zip -j ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-linux.zip ./build/${{ env.PACKAGE_NAME }}-linux/${{ env.PACKAGE_NAME }}
          zip -j ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-macos.zip ./build/${{ env.PACKAGE_NAME }}-macos/${{ env.PACKAGE_NAME }}
          zip -j ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-macos-arm.zip ./build/${{ env.PACKAGE_NAME }}-macos-arm/${{ env.PACKAGE_NAME }}
          zip -j ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-windows.zip ./build/${{ env.PACKAGE_NAME }}-windows/${{ env.PACKAGE_NAME }}.exe

      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          artifacts: './cli/${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-linux.zip,
            ./cli/${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-macos.zip,
            ./cli/${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-macos-arm.zip,
            ./cli/${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-windows.zip'
          tag: 'v${{ env.PACKAGE_VERSION }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          generateReleaseNotes: true
